### ISSUE TITLE
部署时设置默认模型类型

### ISSUE THREAD

**Issue by chenweiask** [Amery2010/TalkWithGemini#10]
现在默认使用Gemini 1.5 flash模型。而我的账号还在waitlist上，所以每次换设备或者换浏览器打开网页，都需要手动重新设置模型。而且模型设置必须输入API key，每次就要开Google页面去查。太麻烦了。
请问是否可以设置一个环境变量，在部署时就确定默认使用的语言模型版本？

**Comment by chenweiask** [comment]
再增加一个，是否可以在部署时定义默认语言？

**Comment by Amery2010** [comment]
可以的
因为我的apiKey默认拥有 Gemini 1.5 Flash 访问权限，因此认为所有账户都有这个权限。
你可以通过以下链接查看是否拥有 Gemini 1.5 Flash 访问权限。
https://generativelanguage.googleapis.com/v1beta/models?key=${apiKey}

**Comment by Amery2010** [comment]
@chenweiask 已支持自定义模型类别及默认模型，会在今天稍晚时候发布新版本

**Comment by chenweiask** [comment]
非常感谢！！！
