### ISSUE TITLE
助理如何使用

### ISSUE THREAD

**Issue by dd0072** [Amery2010/TalkWithGemini#11]
感谢作者开发了这么优秀的软件，我是一个小白，想请教一下助理如何使用

**Comment by Amery2010** [comment]
@dd0072 助理其实就是内置的提示词，有点类似于 GPTs 那种。
举个例子，你如果想要写一篇小红书风格的文章，那么就可以搜索小红书关键词，然后你可以找到一些人之前已经写好的小红书文章写作提示词，这个提示词交给 AI 之后，AI 就可以准确明白你想要做的事什么事情，之后 AI 就以某某专家的模式跟你沟通，这种模式在目前项目中被称之为助理。
