### ISSUE TITLE
1、使用vercel代理api时无法使用语言转文字；2、使用cloudflare代理api时，无法使用报错404

### ISSUE THREAD

**Issue by HQ-random** [Amery2010/TalkWithGemini#12]
![语言转文字](https://github.com/Amery2010/TalkWithGemini/assets/133569887/e7bd2829-71c5-4da0-ad2b-5cac7e959b72)
你好大佬，请教一下：
1、我这边试了下使用GEMINI_API_BASE_URL进行代理（项目：https://github.com/Jazee6/gemini-proxy），无法使用TTS语音转文字；
2、使用[如何部署 Cloudflare Worker api 代理](https://github.com/Amery2010/TalkWithGemini/blob/main/docs/How-to-deploy-the-Cloudflare-Worker-api-proxy.md)时，发现如果不开节点，报错404，有什么好的办法处理吗？
现在也是可以用的，如果有精力的话希望更加的精益求精！！！
感谢感谢

**Comment by Amery2010** [comment]
TTS 无法语音转文字不走代理 api，具体原因请参考常见问题。

CF 代理目前只适合上传。

新版本已经更新，vercel 平台上的项目不再需要设置代理，可以直接上传。
