### ISSUE TITLE
输入的内容不完整会截断

### ISSUE THREAD

**Issue by wwwzhouhui** [Amery2010/TalkWithGemini#13]
在使用过程中聊着聊着 后面信

息返回就截断了
![企业微信截图_17167755134923](https://github.com/Amery2010/TalkWithGemini/assets/355799/35524058-04ae-4856-adc0-a8f3a1f13938)

**Comment by Amery2010** [comment]
你可以检查一下左上角设置页面的参数模型，看你下您当前的屏蔽程度选项是第几个 level，google 默认对部分敏感类信息屏蔽程度较高，如果触发敏感词会直接中断返回。

当然也有可能是新版本的输出逻辑出问题了，当前版本我的确有做了较小的优化，如果经常出现回答截断的问题，我会去复查之前改动过的逻辑。
