### ISSUE TITLE
API代理设置了不起作用

### ISSUE THREAD

**Issue by zhbcher** [Amery2010/TalkWithGemini#14]
不管API代理设置正确还是错误，都不影响

**Comment by Amery2010** [comment]
是部署在 vercel 上的项目还是 docker 自部署的项目，是 GEMINI_API_BASE_URL 无法生效还是 GEMINI_UPLOAD_BASE_URL 无法生效，后者的话有可能是兼容没做好

**Comment by Amery2010** [comment]
@zhbcher 想到一个场景：如果您是在 web 页面设置了 api 代理链接，该链接只在配合 Gemini 密钥的情况下生效，即设置页面的语言模型中的 API 代理链接和 API 下载代理链接都需要有 Gemini 密钥的情况下才生效。关于这个的描述，我后续会考虑增加进常见问题中。

**Comment by zhbcher** [comment]
应用部署在 vercel ，按别的软件应该不用代理，我将数据发送到 vercel 上面，上 vercel 发送到google服务器。这样网络应该是通的。在无魔法上网的时候，不通。我将代理部署在CF上，添加代理后还是不通，在魔法上网时，在WEB设置代理不管正确和错误都可以正常使用。

**Comment by zhbcher** [comment]
谢谢，这个项目非常好，如果能解决这个问题，可以和GPT4o差不多了

**Comment by Amery2010** [comment]
> 应用部署在 vercel ，按别的软件应该不用代理，我将数据发送到 vercel 上面，上 vercel 发送到google服务器。这样网络应该是通的。在无魔法上网的时候，不通。我将代理部署在CF上，添加代理后还是不通，在魔法上网时，在WEB设置代理不管正确和错误都可以正常使用。

你用的是 vercel 提供的域名还是自定义域名？vercel 的域名在中国无法使用，只要自定义一个域名就可以正常用了。

**Comment by zhbcher** [comment]
非常感谢你的答复！
我用的自定义域名，我不魔法上网的时候，是可以访问vercel 部署的项目，
<img width="960" alt="微信图片_20240527134411" src="https://github.com/Amery2010/TalkWithGemini/assets/159907612/49398f7f-82fe-4adc-8bbf-137a821991e8">
就是没办法实现对话，发送消息时报错，设置代理和不设置代理报错都一样，只是错误信息上面地址不一样，设置系统变量和在WEB设置都是一样的。
<img width="960" alt="微信图片_20240527134701" src="https://github.com/Amery2010/TalkWithGemini/assets/159907612/2c657125-98d0-415e-8b87-262271a53afa">

**Comment by zhbcher** [comment]
非常感谢！问题找到了，是google对vercel部分IP 进行封禁，所以造成无法访问，我重新部署一次就可以正常使用了，最近谷歌对IP要求越来越严了。
感谢作者的无私奉献
