### ISSUE TITLE
提示“400: [GoogleGenerativeAI Error]: Candidate was blocked due to SAFETY”

### ISSUE THREAD

**Issue by wjjchen** [Amery2010/TalkWithGemini#17]
在问一些问题的时候同时提示“400: [GoogleGenerativeAI Error]: Candidate was blocked due to SAFETY”，而在gemini.google.com提问相同问题则没有问题。

**Comment by Amery2010** [comment]
看上去是因为回答的问题或内容被屏蔽了。你可以考虑调整 设置-模型设置-屏蔽程度。
