### ISSUE TITLE
Docker部署，语音识别无法使用

### ISSUE THREAD

**Issue by XiaoZ1212** [Amery2010/TalkWithGemini#19]
日本VPS部署，文本和图片都没问题，语音按钮有反馈，但是无法录入声音。手机端显示麦克风权限调用，但没有收录声音。PC和Android浏览器均为最新版Chrome
尝试了您的网站，语音可以正常使用。想了解一下，大概会是什么原因？

**Comment by Amery2010** [comment]
语音识别用的是浏览器的语音识别 api，在常见问题中有描述
