### ISSUE TITLE
Environment variables set in docker deployment do not seem to take effect

### ISSUE THREAD

**Issue by Downstars** [Amery2010/TalkWithGemini#2]
I used docker for deployment and successfully started it,
```shell
docker run -d -p 3000:3000 \
   -e GEMINI_API_KEY=AIza****** \
   -e ACCESS_PASSWORD=****** \
   -e NEXT_PUBLIC_ENABLE_PROTECT=0 \
   xiangfa/talk-with-gemini
```
However, the environment variable parameters I added don't seem to take effect. On the web page, I still have to enter GEMINI_API_KEY to proceed with the Q&A normally, and ACCESS_PASSWORD can be entered with any value.

**Comment by Amery2010** [comment]
If ACCESS_PASSWORD is set, NEXT_PUBLIC_ENABLE_PROTECT needs to be set to 1. This is a problem with my document description. I will improve this part of the description later.
