### ISSUE TITLE
免费计划的API不能用吧？

### ISSUE THREAD

**Issue by wha4up** [Amery2010/TalkWithGemini#21]
如题

**Comment by Amery2010** [comment]
自己试试就清楚了

**Comment by Amery2010** [comment]
你的 key 过期了，只要进入 https://aistudio.google.com/app/apikey 重新申请一个或者更新之前过期的 key 应该就可以了，你需要注意的是，请尽可能创建一个新项目来生成 key，这样不会出现被误认为是付费计划的情况。

**Comment by Amery2010** [comment]
我觉得你是不是可以考虑重新申请一个新的 Google 开发者账号，我觉得你目前的账号似乎被 ban 了。

**Comment by Amery2010** [comment]
> ![image](https://private-user-images.githubusercontent.com/96613608/386339812-d21ccfb7-3f9d-4d6d-b820-09b27393874b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNjE4NTEsIm5iZiI6MTczMjM2MTU1MSwicGF0aCI6Ii85NjYxMzYwOC8zODYzMzk4MTItZDIxY2NmYjctM2Y5ZC00ZDZkLWI4MjAtMDliMjczOTM4NzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDExMzIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MmY2OWE4N2U1Mzc1MzEwMmQzYTIwMzU2ZGViNGRmZDdlMDgwOGE3Zjc5ZTg5OWRkNjRkZWZkNmIwYzMzNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l1PQ8o9BnxC7I75WCO4Vj1NdGRSvQsU1yTxXDu78vpc) 我也出现了

大概率是 Google 账号存在问题，您可以试着重新注册一个账号。
