### ISSUE TITLE
太强大了，比以前部署的好！两个小问题

### ISSUE THREAD

**Issue by zyunling** [Amery2010/TalkWithGemini#22]
1:文本对话都很正常，有些时候上传文件提示失败，关掉科学上网客户端又可以上传，是不是节点有问题？但是同样的节点都可以访问官方的gemini网页和app。

2:语音对话没反应，像是没有接收到话筒输入。
用的是chrome，手机可以正常访问google

**Comment by Amery2010** [comment]
1、你可以检查一下是否设置了代理，最新版本不需要设置上传代理，有时候上传失败有可能是代理那边的问题导致的。
2、问题二的语音对话的问题不好确定，可能是 chrome 的版本较低，不支持最新的浏览器语音识别接口。

我需要更多的信息才能去复现问题所在

**Comment by zyunling** [comment]
> 1、你可以检查一下是否设置了代理，最新版本不需要设置上传代理，有时候上传失败有可能是代理那边的问题导致的。 2、问题二的语音对话的问题不好确定，可能是 chrome 的版本较低，不支持最新的浏览器语音识别接口。
> 
> 我需要更多的信息才能去复现问题所在

1: 我部署只设置了api和密码
2: chrome一直都在play商店更新，是最新版了。

**Comment by Amery2010** [comment]
有一种可能是科学上网工具的协议问题导致的。我之前在浏览其他网页时遇到过类似问题，科学上网工具无法完全兼容比如 ws 协议。

语音对话的问题目前默认使用的是浏览器的语音转文字接口，该接口非常不稳定，后续计划使用 Gemini 1.5 系列的音频识别能力，直接跟 Gemini 沟通。如果你没办法解决目前的情况，只能等几个版本了

**Comment by Amery2010** [comment]
最新版本已支持直接使用语音跟 Gemini 交流，无需借助浏览器的语音识别
