### ISSUE TITLE
手机使用，除了中文，其他语言都发生文字重合

### ISSUE THREAD

**Issue by bestZwei** [Amery2010/TalkWithGemini#23]
![Screenshot_2024-06-02-11-47-09-069_com kiwibrowser browser](https://github.com/Amery2010/TalkWithGemini/assets/110226580/4e096c53-0246-4acc-8a63-3f0fa25edf33)

**Comment by Amery2010** [comment]
感谢反馈
这个问题之前在测试时也遇到过，因为其他语言翻译后的文本自身就很长，除了调整排版意外，目前还没有想到更好的解决方案。
但如果调整排版，那么整个设置页面的 UI，几乎都得重写😑

**Comment by Amery2010** [comment]
下一个大版本会使用 Gemini 1.5 的音频识别能力，实现直接与 Gemini 对话

**Comment by Amery2010** [comment]
The text layout issues have been optimized, and there is no plan to redevelop the UI yet.
The new version already supports direct audio conversation with Gemini.
@bestZwei
