### ISSUE TITLE
语音对话废了

### ISSUE THREAD

**Issue by Fan-Bob** [Amery2010/TalkWithGemini#24]
TTS和stt都寄了

**Comment by Amery2010** [comment]
STT 目前需要科学上网的方式才可以正常使用，具体原因请查看常见问题部分。
TTS 经测试依然可以正常使用，除非微软禁用了 edge 的接口

**Comment by Fan-Bob** [comment]
我人在马来西亚，使用Chrome最新版本浏览器，安卓版本A14

**Comment by Amery2010** [comment]
我目前没有马来西亚的测试环境，暂时无法确定你的问题出于什么原因导致。你可以提供更多的信息，比如浏览器控制台的错误信息。
