### ISSUE TITLE
如何使用cloudflare进行部署呢？

### ISSUE THREAD

**Issue by 1487879421888** [Amery2010/TalkWithGemini#25]
如题：大佬，如何使用cloudflare进行部署呢？

**Comment by Amery2010** [comment]
在 cloudflare 上目前只支持静态部署的方式，即下载 [静态的文件包](https://github.com/Amery2010/TalkWithGemini/releases)，然后上传到 cloudflare page 上即可正常运行。
注意：静态部署的方式只支持科学上网的方式才能使用。

**Comment by 1487879421888** [comment]
感谢答疑，大佬，我在vercel里面部署了，但是，如果，您这边更新了，我如何同步呢！我记得之前有个方式，直接点击upstream即可，我找了，很久，一直不记得在哪里了，希望大佬可以给点启发，感谢。

**Comment by Amery2010** [comment]
在 README 里面有写手动同步的方案，个人并不是建议使用自动同步，如果你想自动同步可以参考 [Upstream Sync](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/README_CN.md#%E4%BF%9D%E6%8C%81%E6%9B%B4%E6%96%B0)
