### ISSUE TITLE
在演示站当中，Gemini重复输出的情况非常频繁和严重，语义衔接不自然，疑似是Bug

### ISSUE THREAD

**Issue by player868** [Amery2010/TalkWithGemini#26]
虽然有时在聊天中看不到这样的情况，但在Gemini输出一卡一卡的情况下，这种情况下很容易发生，特别是在输出不久后的瞬间跳出大量文字时，导致这种bug出现，如图：
![IMG_20240607_211532](https://github.com/Amery2010/TalkWithGemini/assets/129951996/cb1f71fe-36a9-499f-96d4-dd832e906056)

**Comment by Amery2010** [comment]
这个问题，我需要进行进一步的确认，我会进行长文本调试，看看是 api 的问题还是文本输出的问题。
