### ISSUE TITLE
在演示站当中，Gemini重复输出的情况特别的几乎常见且严重，回应段落之间出现了语句断层、重复输出部分内容的现象，疑似是Bug

### ISSUE THREAD

**Issue by player868** [Amery2010/TalkWithGemini#27]
如图所示，这里我做了标记，绿框是原文内容，而红框是重复输出的内容，并且语句断层非常的明显，即使这种断层情况难以察觉。它在通常情况下几乎非常容易触发这样的bug，即使不会触发这样的输出bug也难得一见。不仅如此，其bug表现在回应时的瞬间内涌出大量重复内容的情况下。希望作者能够修复输出问题，因为这对代码生成的方面具有非常大的影响力。
![IMG_20240607_211532](https://github.com/Amery2010/TalkWithGemini/assets/129951996/1cbb9788-c0cf-4290-8d39-f39dada7758d)

**Comment by Amery2010** [comment]
我近期会进行长文本输出调试以确定是 api 的问题还是文本输出逻辑的问题。

**Comment by player868** [comment]
> 我近期会进行长文本输出调试以确定是 api 的问题还是文本输出逻辑的问题。

你目前在演示站有发现什么输出问题吗？

**Comment by Amery2010** [comment]
最近在调试新的功能，暂时还没抽出专门的时间进行长文本调整。目前段文本测试下来除了有时候无法正常保存部分文本之外，还没出现你提到的输出重复文本的情况。

**Comment by player868** [comment]
> 最近在调试新的功能，暂时还没抽出专门的时间进行长文本调整。目前段文本测试下来除了有时候无法正常保存部分文本之外，还没出现你提到的输出重复文本的情况。

那么你先看看新的截图吧，我提供的另外一个演示站截图，在黄色框内，以及下方框内已经很明显的能够感受到输出代码时已经溢出了，而红色分隔线下对应着最上方的内容，彼此之间的输出内容毫无差别。虽然你认为这种Bug可能没有出现在你那里，但在我这里回应长文本总是会出现这种问题。但它的输出机制在我这里问题就是这样的，这个图片可能有点长。而且这种输出问题更容易会发生在长文本回应的尾部中，实在不行的话，我或许可以用视频来作证。我希望能够你理解我所描述的输出问题。
![Screenshot_20240612_153456](https://github.com/Amery2010/TalkWithGemini/assets/129951996/e6d931af-5a0f-414e-87f1-a7df875503ee)

**Comment by Amery2010** [comment]
I found a problem with a section of output logic. I have adjusted this part of the logic. If there is still a problem with the long text output error, please help me describe the steps in which the error occurs.

**Comment by eddiehex** [comment]
> 好的，我这几天会关注并处理这个问题 @player868 我会考虑优化一下文本输出的相关逻辑，这部分逻辑之前实现的有些粗糙，需要优化。
> 
> 我目前需要您提供一些信息，您目前接口是 apikey 直接发送 https://generativelanguage.googleapis.com 这个接口还是通过后端服务进行转发，或者是否有使用代理接口进行转发，我需要模拟您的使用场景。



> 好的，我这几天会关注并处理这个问题 @player868 我会考虑优化一下文本输出的相关逻辑，这部分逻辑之前实现的有些粗糙，需要优化。
> 
> 我目前需要您提供一些信息，您目前接口是 apikey 直接发送 https://generativelanguage.googleapis.com 这个接口还是通过后端服务进行转发，或者是否有使用代理接口进行转发，我需要模拟您的使用场景。

[演示站](https://gemini.u14.app/) 也会出现这种情况，但我没截图

**Comment by Amery2010** [comment]
I have made a code fix today. After the fix, I no longer encountered the error of repeated text rendering when testing. Do you still encounter the problem of repeated text rendering when testing with the latest version? If so, please provide some specific parameters, such as publishing platform, API interface type (backend server, interface transfer agent, direct use of official interface, etc.) @eddiehex

**Comment by eddiehex** [comment]
> I have made a code fix today. After the fix, I no longer encountered the error of repeated text rendering when testing. Do you still encounter the problem of repeated text rendering when testing with the latest version? If so, please provide some specific parameters, such as publishing platform, API interface type (backend server, interface transfer agent, direct use of official interface, etc.) @eddiehex

thanks for your answer, I will take note and feedback to you in time if I run into it again.

**Comment by player532** [comment]
> I have made a code fix today. After the fix, I no longer encountered the error of repeated text rendering when testing. Do you still encounter the problem of repeated text rendering when testing with the latest version? If so, please provide some specific parameters, such as publishing platform, API interface type (backend server, interface transfer agent, direct use of official interface, etc.) [@eddiehex](https://github.com/eddiehex)

@Amery2010 在该issues当中，https://gemini.u14.app/的1.5.0版本的文本编辑→续写功能在长文本测试当中同样出现了该问题，几乎与该issues的问题描述出现的问题完全一样，求作者解决。

**Comment by player532** [comment]
@Amery2010 这里是经过续写处理后的结果及证明
![Image](https://github.com/user-attachments/assets/e41944c1-cd52-4054-bdae-95e686b80519)

**Comment by Amery2010** [comment]
Thanks for the feedback, I have fixed it
