### ISSUE TITLE
How can I change the system prompts so I can make it as  according to me and my requirements for my company bot support and voice support i tried to change prompts.ts code but doesn't work 

### ISSUE THREAD

**Issue by siddharth-coder8** [Amery2010/TalkWithGemini#28]
How can I change the system prompts so I can make it as  according to me and my requirements for my company bot support and voice support i tried to change prompts.ts code but doesn't work

**Comment by Amery2010** [comment]
I need to know your specific usage scenario. If you want to create a new assistant, you can only update it by submitting prompt to [chat-agents](https://github.com/lobehub/lobe-chat-agents). Custom assistants are not supported yet.

If you want to optimize some of the built-in prompts in the current system, you can modify the utils/prompt.ts file. However, under normal circumstances, no adjustment is required. These prompts are used to optimize the reply content and cannot be used in general scenarios.

**Comment by siddharth-coder8** [comment]
I want this ai chatbot should behave as it is the tech support for SVECTOR and it is sync bot and I want it for this and I also tried for changing utils/prompts.ts file the no effect was there @Amery2010

**Comment by Amery2010** [comment]
@siddharth-coder8 
Are you referring to the service of this website [www.svector.co.in](https://www.svector.co.in/)?

I roughly understand your idea. If you want to make an AI customer service robot or a similar AI chat robot, you need to modify the file `app/api/chat/route.ts`, which is the backend service interface. You can add `systemInstruction` to set the system prompt. This parameter can also be sent directly by the frontend.

**Comment by siddharth-coder8** [comment]
Ok thanks 
And yes I was referring to www.svector.co.in/
