### ISSUE TITLE
语音聊天功能无法使用

### ISSUE THREAD

**Issue by haso2007** [Amery2010/TalkWithGemini#3]
docker部署，文字聊天OK,但语音聊天不能使用。前端在android edge和Windows edge都无法实现。
firefox无法打开网站，提示Application error: a client-side exception has occurred (see the browser console for more information).

**Comment by Amery2010** [comment]
目前项目中用到的语音识别接口调用的是浏览器自带的语音识别功能，该功能在 chrome 内核的浏览器上底层是调用 Google 的语音识别接口，该接口需要魔法上网支持否则会无响应。您可以尝试在魔法上网的情况下使用，如果依然有问题，请把您的操作系统和浏览器型号和版本号发给我，我会尽可能找到对应的设备进行调试。
firefox 的问题可能是不支持语音识别接口导致的，我今天下午会考虑做一些处理

**Comment by haso2007** [comment]
用docker部署的无法语音，但是用vercel部署的OK。挺不错的项目，居然没有火，我来推广一下

**Comment by Amery2010** [comment]
> 用docker部署的无法语音，但是用vercel部署的OK。挺不错的项目，居然没有火，我来推广一下

正如我所提到的，目前语音识别的功能需要浏览器的底层支持，部分浏览器需要魔法上网才可以正常使用。我在思考是否可以用第三方的 api 或者本地 whisper-wasm 来作为备用方案。但由于 whisper-wasm 需要额外下载模型，会导致加载慢，目前还在思考可行性。
