### ISSUE TITLE
[Bug] Long Output is generated twice, probably multiple request are sent

### ISSUE THREAD

**Issue by Asoubra12** [Amery2010/TalkWithGemini#34]
### Bug Description

Long Output is generated twice, probably multiple request are sent

### Steps to Reproduce

Send a long prompt, the response contain 2 different outputs 

### Expected Behavior

Single output 

### Deployment Method

- [ ] Docker
- [x] Vercel
- [ ] Server

**Comment by Amery2010** [comment]
OK, I will check the output logic.

**Comment by Amery2010** [comment]
I found a problem with a section of output logic. I have adjusted this part of the logic. If there is still a problem with the long text output error, please help me describe the steps in which the error occurs.
