### ISSUE TITLE
[Bug] 没有找到填写密码的地方

### ISSUE THREAD

**Issue by gray0128** [Amery2010/TalkWithGemini#37]
### Bug Description

感谢作者。
我是用 docker 部署，环境变量中配置了密码，但部署完成之后没有找到输入密码的地方

### Steps to Reproduce

1、打开配置页
2、找不到输入密码的地方

### Expected Behavior

可以输入密码

### Screenshots

![image](https://github.com/Amery2010/TalkWithGemini/assets/7566183/e0a34abe-c1e9-423a-9de2-f0dc76a3f0b1)

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by Amery2010** [comment]
我为了兼容客户端，之前对这部分代码做了调整，可能导致了你描述的这种情况，我需要确认一下导致你目前这个问题的具体原因。

**Comment by Amery2010** [comment]
我临时做了一些修复，很抱歉给您带去了麻烦，您可以拉起最新的镜像进行重新部署。

**Comment by gray0128** [comment]
> 我临时做了一些修复，很抱歉给您带去了麻烦，您可以拉起最新的镜像进行重新部署。

感谢！

**Comment by gray0128** [comment]
> 我临时做了一些修复，很抱歉给您带去了麻烦，您可以拉起最新的镜像进行重新部署。

拉取了最新的，重新部署，还是没有输入密码的地方

**Comment by Amery2010** [comment]
那您尝试拉取 xiangfa/talk-with-gemini:v0.12.1 这个版本，latest 版本可能会被缓存成之前的版本
