### ISSUE TITLE
[Feature Request]: 附件支持pdf

### ISSUE THREAD

**Issue by Ufitok** [Amery2010/TalkWithGemini#38]
### Problem Description

现在很多桌面应用都没有设置附件功能，同样pdf也没有。当然，我指的是向你这种免费的、极好的应用！

### Solution Description

我不知道这个实施起来是不是有难度，不过目前已经做得很好了，虽然这并不是对我

**Comment by Amery2010** [comment]
关于目前附件上传的问题，请阅读常见问题中的 [为什么我无法上传 doc、excel、pdf 这类常见文档](https://github.com/Amery2010/TalkWithGemini?tab=readme-ov-file#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E6%97%A0%E6%B3%95%E4%B8%8A%E4%BC%A0-docexcelpdf-%E8%BF%99%E7%B1%BB%E5%B8%B8%E8%A7%81%E6%96%87%E6%A1%A3)

目前官方 api 支持的附件包含大部分的图片、音频、视频和部分文本类的文件。

**Comment by Amery2010** [comment]
官方已支持 PDF，新版本已允许上传 PDF 文件
