### ISSUE TITLE
在演示站中，代码板块内的非代码内容的输出为“null”，无法进行正常输出。

### ISSUE THREAD

**Issue by player868** [Amery2010/TalkWithGemini#39]
如图，只有在非代码在代码板块内输出是异常的，而代码板块的代码输出则是正常的
![Screenshot_20240630_075637](https://github.com/Amery2010/TalkWithGemini/assets/129951996/9b1ef3ff-367f-4b85-aa69-c323b81e9881)

**Comment by Amery2010** [comment]
这个应该属于 Gemini 的输出问题，我尝试了你的问题，输出结果正常
![WX20240702-182139@2x](https://github.com/Amery2010/TalkWithGemini/assets/5876036/ac1a9417-0353-479e-99fc-ef4d4d691c0c)

同时我也观察了代码板块为 null 的情况，由于目前是流式内容输出，如果代码片段未完整输出，代码块的代码就默认为 null。
