### ISSUE TITLE
希望支持Gemini pro 1.5

### ISSUE THREAD

**Issue by nuclearn** [Amery2010/TalkWithGemini#4]
看了一下，目前好像只支持pro 1.0版本，1.5版本提升相当大，而且是多模态的，估计修改的地方有点多。

**Comment by Amery2010** [comment]
> 看了一下，目前好像只支持pro 1.0版本，1.5版本提升相当大，而且是多模态的，估计修改的地方有点多。

 已经在开发计划中了，不过 1.5 的 api 请求数比较少，每分钟 2次，一天限制 100次，因此不会作为首选项
