### ISSUE TITLE
在演示站当中，这种错误经常会出现，望作者修复

### ISSUE THREAD

**Issue by player868** [Amery2010/TalkWithGemini#40]
![Screenshot_20240703_001219](https://github.com/Amery2010/TalkWithGemini/assets/129951996/c0b745b7-4c46-4d4a-a0e6-7f69dab03bcb)

**Comment by Amery2010** [comment]
Gemini-Pro 每天的免费次数有限（可以查看官方的说明），且每分钟限制 2次，超过次数就会响应失败

注意：演示站只是用于尝试 Gemini 的能力，由于 api key 共用，响应次数很容易达到每日上限，请不要当成个人 AI 助理使用。如果有长期使用需求，请参考流程一键部署属于自己的 Gemini 服务
