### ISSUE TITLE
演示站中的gemini-1.0-pro-vision版本模型无法使用

### ISSUE THREAD

**Issue by player868** [Amery2010/TalkWithGemini#41]
![Screenshot_20240703_081416](https://github.com/Amery2010/TalkWithGemini/assets/129951996/a2351d1d-4f4a-43c5-a329-f292256c0bf7)
![Screenshot_20240703_080524](https://github.com/Amery2010/TalkWithGemini/assets/129951996/b93ec869-71c9-41ba-8d4b-c34195cce1fa)

**Comment by Amery2010** [comment]
我刚查看了模型列表，gemini-1.0-pro-vision 这个已经被官方下线了，请使用 gemini-1.0-pro-vision-latest 或 gemini-pro-vision 替代
