### ISSUE TITLE
Does it support API, if not add this feature because we need it[Feature Request]: 

### ISSUE THREAD

**Issue by OS-OFC** [Amery2010/TalkWithGemini#43]
add  API

**Comment by Amery2010** [comment]
The project is implemented based on Gemini API. If you need to use Gemini API, you can directly refer to [the official documentation](https://ai.google.dev/docs/).

The project does have some [backend APIs](https://github.com/Amery2010/TalkWithGemini/tree/main/app/api) (limited to deployment methods that include a server, such as vercel or docker), but these APIs are for internal use and only perform simple permission verification, and are not suitable for other production services.

You can describe your specific API requirements and I will consider the feasibility of implementation.
