### ISSUE TITLE
[Bug] 400: [GoogleGenerativeAI Error]

### ISSUE THREAD

**Issue by walterfang1209** [Amery2010/TalkWithGemini#45]
### Bug Description

对话时提示 `400: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:streamGenerateContent?alt=sse: [400 ] Gemini API free tier is not available in your country. Please enable billing on your project in Google AI Studio.`。我确保我的 `api` 没有问题。

### Steps to Reproduce

无法复现

### Expected Behavior

fix as soon

### Deployment Method

- [ ] Docker
- [x] Vercel
- [ ] Server

**Comment by keethebest** [comment]
我可以用，应该是你使用的代理的ip问题。

**Comment by darthalex2014** [comment]
Use USA Vpn, or use another Api key.

**Comment by Amery2010** [comment]
也许您可以考虑申请新的 api key，或者使用新的 google 账号申请新的 api key。之前有其他用户遇到类似的 api key 的问题，最后发现时账号被 google 管控了，因此无法正常使用。

如果您觉得不是 api key 的问题，有可能是接口代理的问题，您可以部署一个 Vercel 版本进行测试（需要填写服务端变量）
