### ISSUE TITLE
[Feature Request]: add model gemini-1.5-pro-exp-0801 and adding a confirmation prompt before "Clear Chat Content"

### ISSUE THREAD

**Issue by darthalex2014** [Amery2010/TalkWithGemini#46]
### Problem Description

I'm currently unable to use the gemini-1.5-pro-exp-0801 model with this repository.

Additionally, the "Clear Chat Content" button at the bottom of the chat interface is easily accidentally pressed, especially on mobile devices. This can lead to unintentional loss of the entire chat history, which is frustrating and disruptive.

### Solution Description

I would like the repository author to add support for the gemini-1.5-pro-exp-0801 model.

Furthermore, I propose adding a confirmation prompt before clearing the chat content. This could be a simple pop-up dialog asking the user to confirm their action. This would prevent accidental clearing of the chat history and improve the overall user experience, particularly on mobile devices.

**Comment by Amery2010** [comment]
If you want to use a new model, you can expand it by customizing the model list without updating the version.
```txt
NEXT_PUBLIC_GEMINI_MODEL_LIST=+all,+gemini-1.5-pro-exp-0801
```

The button to clear the chat content will be adjusted in subsequent versions

**Comment by darthalex2014** [comment]
> If you want to use a new model, you can expand it by customizing the model list without updating the version.
> 
> ```
> NEXT_PUBLIC_GEMINI_MODEL_LIST=+all,+gemini-1.5-pro-exp-0801
> ```
> 
> The button to clear the chat content will be adjusted in subsequent versions

im simple add gemini-1.5-pro-exp-0801 to model list.

**Comment by darthalex2014** [comment]
vercel automated enter changes in github.

**Comment by Amery2010** [comment]
The latest version supports getting the latest model list
