### ISSUE TITLE
[Feature Request]: 后台生成回答内容

### ISSUE THREAD

**Issue by zjsdn** [Amery2010/TalkWithGemini#49]
### Problem Description

大佬，是这样，我输入问题后，切换到别的应用程序，离开当前页面，回答就不在继续生成了，只有切换回回答页面，回答才会继续

### Solution Description

大佬后续是否考虑优化这个后台回答的功能，不然的话只能停留在当前页面等待回答完成

**Comment by Amery2010** [comment]
这个应该不是代码层面的问题，而是浏览器的机制问题。据我所知，Chrome 浏览器（包括Chrome内核的所有浏览器），在离开当前页面后会进入半休眠状态（为了节约内存和cpu开销），半休眠状态下应该会出现您提到的这种情况。
您可以考虑试试 App 版本，App 版本使用的是独立内核，应该会避免进入半休眠状态

**Comment by zjsdn** [comment]
> 这个应该不是代码层面的问题，而是浏览器的机制问题。据我所知，Chrome 浏览器（包括Chrome内核的所有浏览器），在离开当前页面后会进入半休眠状态（为了节约内存和cpu开销），半休眠状态下应该会出现您提到的这种情况。 您可以考虑试试 App 版本，App 版本使用的是独立内核，应该会避免进入半休眠状态

好的，谢谢大佬
