### ISSUE TITLE
支持多gemini key

### ISSUE THREAD

**Issue by gochendong** [Amery2010/TalkWithGemini#5]
gemini请求限制应该是基于key的, 所以支持多个key可以增加并发量

**Comment by Amery2010** [comment]
有考虑过这个需求，只不过目前我只有一个 key，需要多找几个 key 才可以做并发测试。
预计下个版本就会增加多 key 支持

**Comment by heiyyint** [comment]
能否支持中转key，接口路径/v1/chat/completions

**Comment by Amery2010** [comment]
> 能否支持中转key，接口路径/v1/chat/completions

中转可以通过同时设置 GEMINI_API_KEY 和 GEMINI_API_BASE_URL 来实现，但目前只能使用 Gemini 官方 api 的形式接口，无法兼容 openai 形式的接口

**Comment by heiyyint** [comment]
> > 能否支持中转key，接口路径/v1/chat/completions
> 
> 中转可以通过同时设置 GEMINI_API_KEY 和 GEMINI_API_BASE_URL 来实现，但目前只能使用 Gemini 官方 api 的形式接口，无法兼容 openai 形式的接口

对，这个我看到了，接口路径的确是走官方的，用的是官方接口的那个依赖包？

**Comment by Amery2010** [comment]
> > > 能否支持中转key，接口路径/v1/chat/completions
> > 
> > 
> > 中转可以通过同时设置 GEMINI_API_KEY 和 GEMINI_API_BASE_URL 来实现，但目前只能使用 Gemini 官方 api 的形式接口，无法兼容 openai 形式的接口
> 
> 对，这个我看到了，接口路径的确是走官方的，用的是官方接口的那个依赖包？

是的，在 package.json 里有作为依赖

oneapi 没怎么研究过，估计没办法直接做兼容，那个项目似乎是以 openai 形式的接口为统一接口形式，即将 Gemini 接口转为 openai 形式，而 openai 形式的接口没办法完全满足 Gemini 1.5 Pro 和 Gemini 1.5 Flash 的全部功能。

**Comment by heiyyint** [comment]
> > > > 能否支持中转key，接口路径/v1/chat/completions
> > > 
> > > 
> > > 中转可以通过同时设置 GEMINI_API_KEY 和 GEMINI_API_BASE_URL 来实现，但目前只能使用 Gemini 官方 api 的形式接口，无法兼容 openai 形式的接口
> > 
> > 对，这个我看到了，接口路径的确是走官方的，用的是官方接口的那个依赖包？
> 
> 是的，在 package.json 里有作为依赖
> 
> oneapi 没怎么研究过，估计没办法直接做兼容，那个项目似乎是以 openai 形式的接口为统一接口形式，即将 Gemini 接口转为 openai 形式，而 openai 形式的接口没办法完全满足 Gemini 1.5 Pro 和 Gemini 1.5 Flash 的全部功能。

也就是说走oneapi没法支持视频？

**Comment by Amery2010** [comment]
> > > > > 能否支持中转key，接口路径/v1/chat/completions
> > > > 
> > > > 
> > > > 中转可以通过同时设置 GEMINI_API_KEY 和 GEMINI_API_BASE_URL 来实现，但目前只能使用 Gemini 官方 api 的形式接口，无法兼容 openai 形式的接口
> > > 
> > > 
> > > 对，这个我看到了，接口路径的确是走官方的，用的是官方接口的那个依赖包？
> > 
> > 
> > 是的，在 package.json 里有作为依赖
> > oneapi 没怎么研究过，估计没办法直接做兼容，那个项目似乎是以 openai 形式的接口为统一接口形式，即将 Gemini 接口转为 openai 形式，而 openai 形式的接口没办法完全满足 Gemini 1.5 Pro 和 Gemini 1.5 Flash 的全部功能。
> 
> 也就是说走oneapi没法支持视频？

你可以在 oneapi 项目下开一个 issues 来确认，本人的确对 oneapi 项目不是很清楚

**Comment by heiyyint** [comment]
> > > > > > 能否支持中转key，接口路径/v1/chat/completions
> > > > > 
> > > > > 
> > > > > 中转可以通过同时设置 GEMINI_API_KEY 和 GEMINI_API_BASE_URL 来实现，但目前只能使用 Gemini 官方 api 的形式接口，无法兼容 openai 形式的接口
> > > > 
> > > > 
> > > > 对，这个我看到了，接口路径的确是走官方的，用的是官方接口的那个依赖包？
> > > 
> > > 
> > > 是的，在 package.json 里有作为依赖
> > > oneapi 没怎么研究过，估计没办法直接做兼容，那个项目似乎是以 openai 形式的接口为统一接口形式，即将 Gemini 接口转为 openai 形式，而 openai 形式的接口没办法完全满足 Gemini 1.5 Pro 和 Gemini 1.5 Flash 的全部功能。
> > 
> > 也就是说走oneapi没法支持视频？
> 
> 你可以在 oneapi 项目下开一个 issues 来确认，本人的确对 oneapi 项目不是很清楚

好的，感谢

**Comment by Amery2010** [comment]
> gemini请求限制应该是基于key的, 所以支持多个key可以增加并发量

我今天试着开发对多 key 的支持，但发现一个严重的问题，Gemini 1.5 系列的接口如果用到文件上传功能，那么多 key 就会出现问题。文件上传需要用到 key，且是跟 key 绑定的，如果上传文件用的是 A key，如果某次回答消失时用的是 B key，那么就会产生无权限访问 A key 文件的错误，这个无法解决的权限问题。

如果需要支持多 key，就需要做一套缓存系统，且要将每次对话生成对应的 session，即对话绑定 key。这样一来整个系统就会变得很复杂，暂时不在考虑对多 key 的支持。
