### ISSUE TITLE
Gemini-1.5-flash-exp-0827 现已推出

### ISSUE THREAD

**Issue by player868** [Amery2010/TalkWithGemini#51]
作者考虑将该模型添加至默认模型列表内吗？
![Screenshot_20240912_203727](https://github.com/user-attachments/assets/51d996a7-0dda-413a-9aef-4cd873ce0d1c)

**Comment by Amery2010** [comment]
好的，我会考虑将这些实验性的模型加入到模型列表，目前可以通过自定义模型列表来使用

**Comment by Amery2010** [comment]
最新的 v0.12.3 版本已经支持用户模型列表获取
