### ISSUE TITLE
一个小小的建议

### ISSUE THREAD

**Issue by player868** [Amery2010/TalkWithGemini#55]
作者是否能够考虑并实现该功能：当我按下回车键时，实际上它会切换至下一行，而不会直接发送对话内容至AI。如果可以的话，也能够给该功能单独做一个开关选项，来决定是否启用该功能，以达到更加人性化的效果。在某些情况下，我认为还是有必要的……

**Comment by Amery2010** [comment]
这个功能之前尝试开发过，当在整体体验不是很理想，会使得输入速度更慢。
目前在 PC 端支持 shift+enter 组合键进行换行（算是一个小的隐藏功能）
