### ISSUE TITLE
项目很好, 值得更多star, 我就多提点意见了, 

### ISSUE THREAD

**Issue by gochendong** [Amery2010/TalkWithGemini#6]
1. 支持设置默认安全等级, 最低应该是BLOCK_NONE, 现在是BLOCK_HIGH, 算是倒数第二低
2. 支持关闭语言自动朗读功能,  录音界面考虑将最近一次回复保留, 而不是很快就消失了? 
3. 支持从剪切板粘贴图片/文件
4. 支持自定义前端页面可选模型列表, 像这样-all,+gemini-1.5-flash-latest
5. 进入页面后自动聚焦输入框

更多... 我再想想

**Comment by gochendong** [comment]
6. 支持自定义temperature和top_p 
```
generation_config = {
  "temperature": 1,
  "top_p": 0.95,
  "top_k": 64,
  "max_output_tokens": 8192,
  "response_mime_type": "text/plain",
}
```

**Comment by gochendong** [comment]
7. 刚才正好gemini挂了 发现状态码是写死400的, 这里写500比较好

**Comment by gochendong** [comment]
8. "title": "与 Gemini Pro 交谈", 这个文案是不是应该改下了, Gemini就好

**Comment by Amery2010** [comment]
> 1. 支持设置默认安全等级, 最低应该是BLOCK_NONE, 现在是BLOCK_HIGH, 算是倒数第二低
> 2. 支持关闭语言自动朗读功能,  录音界面考虑将最近一次回复保留, 而不是很快就消失了?
> 3. 支持从剪切板粘贴图片/文件
> 4. 支持自定义前端页面可选模型列表, 像这样-all,+gemini-1.5-flash-latest
> 5. 进入页面后自动聚焦输入框
> 
> 更多... 我再想想

好的，你的这些建议我会好好考虑的，有一些是已经计划开发的功能，比如设置页面会增加 Gemini 的参数设置。

语音对话模式在当前项目做可能不会再做大的拓展，后续会以改功能为基础开发新的项目，功能类似于 Gemini live

关于问题 7，能否详细描述一下具体的复现流程，我可以作为错误定位的依据。

**Comment by gochendong** [comment]
> > 1. 支持设置默认安全等级, 最低应该是BLOCK_NONE, 现在是BLOCK_HIGH, 算是倒数第二低
> > 2. 支持关闭语言自动朗读功能,  录音界面考虑将最近一次回复保留, 而不是很快就消失了?
> > 3. 支持从剪切板粘贴图片/文件
> > 4. 支持自定义前端页面可选模型列表, 像这样-all,+gemini-1.5-flash-latest
> > 5. 进入页面后自动聚焦输入框
> > 
> > 更多... 我再想想
> 
> 好的，你的这些建议我会好好考虑的，有一些是已经计划开发的功能，比如设置页面会增加 Gemini 的参数设置。
> 
> 语音对话模式在当前项目做可能不会再做大的拓展，后续会以改功能为基础开发新的项目，功能类似于 Gemini live
> 
> 关于问题 7，能否详细描述一下具体的复现流程，我可以作为错误定位的依据。

就在今天gemini服务器出了好几次故障, 服务器直接返回500, 在talkwithgemini上展示的内容就是400 server error

**Comment by Amery2010** [comment]
> > > 1. 支持设置默认安全等级, 最低应该是BLOCK_NONE, 现在是BLOCK_HIGH, 算是倒数第二低
> > > 2. 支持关闭语言自动朗读功能,  录音界面考虑将最近一次回复保留, 而不是很快就消失了?
> > > 3. 支持从剪切板粘贴图片/文件
> > > 4. 支持自定义前端页面可选模型列表, 像这样-all,+gemini-1.5-flash-latest
> > > 5. 进入页面后自动聚焦输入框
> > > 
> > > 更多... 我再想想
> > 
> > 
> > 好的，你的这些建议我会好好考虑的，有一些是已经计划开发的功能，比如设置页面会增加 Gemini 的参数设置。
> > 语音对话模式在当前项目做可能不会再做大的拓展，后续会以改功能为基础开发新的项目，功能类似于 Gemini live
> > 关于问题 7，能否详细描述一下具体的复现流程，我可以作为错误定位的依据。
> 
> 就在今天gemini服务器出了好几次故障, 服务器直接返回500, 在talkwithgemini上展示的内容就是400 server error

我大概清楚了，我回头看一下

**Comment by gochendong** [comment]
9. 支持pwa

**Comment by Amery2010** [comment]
@gochendong 已完成除了 2 以外的所有功能，语音对话暂时不做调整
