### ISSUE TITLE
没有清除单条聊天记录的按钮

### ISSUE THREAD

**Issue by heiyyint** [Amery2010/TalkWithGemini#8]
因为清除单条聊天记录之后对话就不会上传到那条的上下文

**Comment by Amery2010** [comment]
是的，之前没有考虑实现细节问题，后续会考虑增加对聊天内容编辑、删除、复制和朗读等功能

**Comment by heiyyint** [comment]
> 是的，之前没有考虑实现细节问题，后续会考虑增加对聊天内容编辑、删除、复制和朗读等功能

好

**Comment by Amery2010** [comment]
已增加对聊天内容的重新生成、编辑、删除、复制和朗读功能，新版本将在下周一（5月27号）发布
