### ISSUE TITLE
语音交互新方式--优化建议

### ISSUE THREAD

**Issue by stone100010** [Amery2010/TalkWithGemini#9]
语音交互新方式，推荐看一下《通义千问APP》，具体使用表现为：后台会等待用户不说话后自动回复，无需每次人工终止录音内容
关于“侦听用户输入结束”，这可能会增加判断逻辑和计算量，但从用户角度上确实很人性化和智能化，有更加优质的体验。

非常感谢也给非常荣幸看到国人开发者介入ChatGPT语音交互新方式，加油，原创作者团队非常棒！

**Comment by Amery2010** [comment]
> 语音交互新方式，推荐看一下《通义千问APP》，具体使用表现为：后台会等待用户不说话后自动回复，无需每次人工终止录音内容 关于“侦听用户输入结束”，这可能会增加判断逻辑和计算量，但从用户角度上确实很人性化和智能化，有更加优质的体验。
> 
> 非常感谢也给非常荣幸看到国人开发者介入ChatGPT语音交互新方式，加油，原创作者团队非常棒！

其实我最初开发的原型就是这样的，那时候是参照 ChatGPT语音交互来实现的，但那时候遇到一个问题，正常交互没问题，但如果用户长时间不说话，期间环境噪音短时过大，会被动触发录音结束的，会导致出现意外的数据提交，会让用户觉得应用在自说自话，这是一种很不好的体验。如果要解决这个问题，需要时时判断录音输入内容，判断是否为有效录音，如果不借助语义检测工具（没找到这类轻量级的工具库）的话，没有其他很好的解决方式。

在没有找到比较好的解决方案前，语音对话功能的开发优先级会较低。不过会考虑将你提到的这个需求作为一个配置选项，可以手动开启。

**Comment by chenweiask** [comment]
对于语音的界面交互，我有个建议，就是类似于对讲机的使用方法，从按下按钮开始录音，一直到释放按钮。
另外，关于语言的识别，目前效果并不好。所以得在设置里选择语言。考虑到很多人有双语需求，每次切换都进设置比较麻烦，可以考虑把上面对讲机的按钮设置成两个，一个对应语言一，另一个对应语言二。语言一和二可以在设置里定义语种。
